.TH PROJECT "1" "Fev 1999" "project 0.000" "User Commands"
.SH NAME
project \- Project description
.SH SYNOPSIS
.B project
[\fIOPTION\fR]
[\fIFILE\fR]...
.SH DESCRIPTION
.PP
Currently is only suported short options.
.TP
\fB\-v\fR
set verbose mode
.SH AUTHOR
Written by Alexandre F Muller Souza.
.SH "REPORTING BUGS"
Report bugs to <alexandrefelipemuller@gmail.com>.
.SH COPYRIGHT
Copyright \(co 2007 by author.
.br
This is free software.  You may redistribute copies of it under the terms of
the BERKELEY SOFTWARE DISTRIBUTION.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
.B file (1)
.B project.conf (5)
